/*
 * This file is generated by jOOQ.
 */
package io.github.oclay1st.vrs.autogenerated.jooq;


import io.github.oclay1st.vrs.autogenerated.jooq.tables.User;
import io.github.oclay1st.vrs.autogenerated.jooq.tables.Vehicle;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>vehicle</code>.
     */
    public final Vehicle VEHICLE = Vehicle.VEHICLE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            User.USER,
            Vehicle.VEHICLE
        );
    }
}
