/*
 * This file is generated by jOOQ.
 */
package io.github.oclay1st.vrs.autogenerated.jooq;


import io.github.oclay1st.vrs.autogenerated.jooq.tables.ArchivedVehicle;
import io.github.oclay1st.vrs.autogenerated.jooq.tables.User;
import io.github.oclay1st.vrs.autogenerated.jooq.tables.Vehicle;
import io.github.oclay1st.vrs.autogenerated.jooq.tables.records.ArchivedVehicleRecord;
import io.github.oclay1st.vrs.autogenerated.jooq.tables.records.UserRecord;
import io.github.oclay1st.vrs.autogenerated.jooq.tables.records.VehicleRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ArchivedVehicleRecord> ARCHIVED_VEHICLE_PK = Internal.createUniqueKey(ArchivedVehicle.ARCHIVED_VEHICLE, DSL.name("archived_vehicle_pk"), new TableField[] { ArchivedVehicle.ARCHIVED_VEHICLE.ID }, true);
    public static final UniqueKey<UserRecord> USER_PK = Internal.createUniqueKey(User.USER, DSL.name("user_pk"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<VehicleRecord> CONSTRAINT_1 = Internal.createUniqueKey(Vehicle.VEHICLE, DSL.name("CONSTRAINT_1"), new TableField[] { Vehicle.VEHICLE.LICENSE_PLATE }, true);
    public static final UniqueKey<VehicleRecord> VEHICLE_PK = Internal.createUniqueKey(Vehicle.VEHICLE, DSL.name("vehicle_pk"), new TableField[] { Vehicle.VEHICLE.VIN }, true);
}
