/*
 * This file is generated by jOOQ.
 */
package io.github.oclay1st.vrs.autogenerated.jooq;


import io.github.oclay1st.vrs.autogenerated.jooq.tables.ArchivedVehicle;
import io.github.oclay1st.vrs.autogenerated.jooq.tables.User;
import io.github.oclay1st.vrs.autogenerated.jooq.tables.Vehicle;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>archived_vehicle</code>.
     */
    public static final ArchivedVehicle ARCHIVED_VEHICLE = ArchivedVehicle.ARCHIVED_VEHICLE;

    /**
     * The table <code>user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>vehicle</code>.
     */
    public static final Vehicle VEHICLE = Vehicle.VEHICLE;
}
