/*
 * This file is generated by jOOQ.
 */
package io.github.oclay1st.vrs.autogenerated.jooq.tables.records;


import io.github.oclay1st.vrs.autogenerated.jooq.tables.ArchivedVehicle;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArchivedVehicleRecord extends UpdatableRecordImpl<ArchivedVehicleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>archived_vehicle.id</code>.
     */
    public ArchivedVehicleRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>archived_vehicle.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>archived_vehicle.vin</code>.
     */
    public ArchivedVehicleRecord setVin(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>archived_vehicle.vin</code>.
     */
    public Long getVin() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>archived_vehicle.license_plate</code>.
     */
    public ArchivedVehicleRecord setLicensePlate(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>archived_vehicle.license_plate</code>.
     */
    public String getLicensePlate() {
        return (String) get(2);
    }

    /**
     * Setter for <code>archived_vehicle.type</code>.
     */
    public ArchivedVehicleRecord setType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>archived_vehicle.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>archived_vehicle.diesel_injection_pump_type</code>.
     */
    public ArchivedVehicleRecord setDieselInjectionPumpType(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>archived_vehicle.diesel_injection_pump_type</code>.
     */
    public String getDieselInjectionPumpType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>archived_vehicle.gas_fuel_types</code>.
     */
    public ArchivedVehicleRecord setGasFuelTypes(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>archived_vehicle.gas_fuel_types</code>.
     */
    public String getGasFuelTypes() {
        return (String) get(5);
    }

    /**
     * Setter for <code>archived_vehicle.battery_type</code>.
     */
    public ArchivedVehicleRecord setBatteryType(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>archived_vehicle.battery_type</code>.
     */
    public String getBatteryType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>archived_vehicle.battery_voltage</code>.
     */
    public ArchivedVehicleRecord setBatteryVoltage(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>archived_vehicle.battery_voltage</code>.
     */
    public Integer getBatteryVoltage() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>archived_vehicle.battery_amperage</code>.
     */
    public ArchivedVehicleRecord setBatteryAmperage(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>archived_vehicle.battery_amperage</code>.
     */
    public Integer getBatteryAmperage() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>archived_vehicle.registered_at</code>.
     */
    public ArchivedVehicleRecord setRegisteredAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>archived_vehicle.registered_at</code>.
     */
    public LocalDateTime getRegisteredAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>archived_vehicle.archived_at</code>.
     */
    public ArchivedVehicleRecord setArchivedAt(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>archived_vehicle.archived_at</code>.
     */
    public LocalDateTime getArchivedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArchivedVehicleRecord
     */
    public ArchivedVehicleRecord() {
        super(ArchivedVehicle.ARCHIVED_VEHICLE);
    }

    /**
     * Create a detached, initialised ArchivedVehicleRecord
     */
    public ArchivedVehicleRecord(Long id, Long vin, String licensePlate, String type, String dieselInjectionPumpType, String gasFuelTypes, String batteryType, Integer batteryVoltage, Integer batteryAmperage, LocalDateTime registeredAt, LocalDateTime archivedAt) {
        super(ArchivedVehicle.ARCHIVED_VEHICLE);

        setId(id);
        setVin(vin);
        setLicensePlate(licensePlate);
        setType(type);
        setDieselInjectionPumpType(dieselInjectionPumpType);
        setGasFuelTypes(gasFuelTypes);
        setBatteryType(batteryType);
        setBatteryVoltage(batteryVoltage);
        setBatteryAmperage(batteryAmperage);
        setRegisteredAt(registeredAt);
        setArchivedAt(archivedAt);
        resetChangedOnNotNull();
    }
}
