/*
 * This file is generated by jOOQ.
 */
package io.github.oclay1st.vrs.autogenerated.jooq.tables.records;


import io.github.oclay1st.vrs.autogenerated.jooq.tables.Vehicle;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VehicleRecord extends UpdatableRecordImpl<VehicleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vehicle.vin</code>.
     */
    public VehicleRecord setVin(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.vin</code>.
     */
    public Long getVin() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>vehicle.license_plate</code>.
     */
    public VehicleRecord setLicensePlate(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.license_plate</code>.
     */
    public String getLicensePlate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vehicle.type</code>.
     */
    public VehicleRecord setType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vehicle.diesel_injection_pump_type</code>.
     */
    public VehicleRecord setDieselInjectionPumpType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.diesel_injection_pump_type</code>.
     */
    public String getDieselInjectionPumpType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vehicle.gas_fuel_types</code>.
     */
    public VehicleRecord setGasFuelTypes(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.gas_fuel_types</code>.
     */
    public String getGasFuelTypes() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vehicle.battery_type</code>.
     */
    public VehicleRecord setBatteryType(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.battery_type</code>.
     */
    public String getBatteryType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>vehicle.battery_voltage</code>.
     */
    public VehicleRecord setBatteryVoltage(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.battery_voltage</code>.
     */
    public Integer getBatteryVoltage() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>vehicle.battery_amperage</code>.
     */
    public VehicleRecord setBatteryAmperage(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.battery_amperage</code>.
     */
    public Integer getBatteryAmperage() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>vehicle.convertible</code>.
     */
    public VehicleRecord setConvertible(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.convertible</code>.
     */
    public Boolean getConvertible() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>vehicle.convertible_license_plate</code>.
     */
    public VehicleRecord setConvertibleLicensePlate(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.convertible_license_plate</code>.
     */
    public String getConvertibleLicensePlate() {
        return (String) get(9);
    }

    /**
     * Setter for <code>vehicle.convertible_gas_fuel_types</code>.
     */
    public VehicleRecord setConvertibleGasFuelTypes(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.convertible_gas_fuel_types</code>.
     */
    public String getConvertibleGasFuelTypes() {
        return (String) get(10);
    }

    /**
     * Setter for <code>vehicle.user_id</code>.
     */
    public VehicleRecord setUserId(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>vehicle.created_at</code>.
     */
    public VehicleRecord setCreatedAt(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>vehicle.updated_at</code>.
     */
    public VehicleRecord setUpdatedAt(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehicleRecord
     */
    public VehicleRecord() {
        super(Vehicle.VEHICLE);
    }

    /**
     * Create a detached, initialised VehicleRecord
     */
    public VehicleRecord(Long vin, String licensePlate, String type, String dieselInjectionPumpType, String gasFuelTypes, String batteryType, Integer batteryVoltage, Integer batteryAmperage, Boolean convertible, String convertibleLicensePlate, String convertibleGasFuelTypes, Long userId, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Vehicle.VEHICLE);

        setVin(vin);
        setLicensePlate(licensePlate);
        setType(type);
        setDieselInjectionPumpType(dieselInjectionPumpType);
        setGasFuelTypes(gasFuelTypes);
        setBatteryType(batteryType);
        setBatteryVoltage(batteryVoltage);
        setBatteryAmperage(batteryAmperage);
        setConvertible(convertible);
        setConvertibleLicensePlate(convertibleLicensePlate);
        setConvertibleGasFuelTypes(convertibleGasFuelTypes);
        setUserId(userId);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
