/*
 * This file is generated by jOOQ.
 */
package io.github.oclay1st.vrs.autogenerated.jooq.tables.records;


import io.github.oclay1st.vrs.autogenerated.jooq.tables.Vehicle;

import java.time.LocalDateTime;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VehicleRecord extends UpdatableRecordImpl<VehicleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vehicle.vin</code>.
     */
    public VehicleRecord setVin(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.vin</code>.
     */
    public Long getVin() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>vehicle.license_plate</code>.
     */
    public VehicleRecord setLicensePlate(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.license_plate</code>.
     */
    public String getLicensePlate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vehicle.type</code>.
     */
    public VehicleRecord setType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vehicle.details</code>.
     */
    public VehicleRecord setDetails(JSON value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.details</code>.
     */
    public JSON getDetails() {
        return (JSON) get(3);
    }

    /**
     * Setter for <code>vehicle.created_at</code>.
     */
    public VehicleRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>vehicle.updated_at</code>.
     */
    public VehicleRecord setUpdatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vehicle.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehicleRecord
     */
    public VehicleRecord() {
        super(Vehicle.VEHICLE);
    }

    /**
     * Create a detached, initialised VehicleRecord
     */
    public VehicleRecord(Long vin, String licensePlate, String type, JSON details, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Vehicle.VEHICLE);

        setVin(vin);
        setLicensePlate(licensePlate);
        setType(type);
        setDetails(details);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
