package io.github.oclay1st.vrs.modules.security.auth.infrastructure.repository;

import org.jooq.DSLContext;
import org.springframework.stereotype.Repository;

import java.util.Optional;

import static io.github.oclay1st.vrs.autogenerated.jooq.tables.User.USER;

@Repository
public class JooQUserSecurityRepository implements UserSecurityRepository {

    private final DSLContext client;

    public JooQUserSecurityRepository(DSLContext client) {
        this.client = client;
    }

    @Override
    public Optional<UserSecurity> findByUsername(String username) {
        return client.selectFrom(USER)
                .where(USER.USERNAME.eq(username))
                .fetchOptional(user -> new UserSecurity(user.getUsername(), user.getPassword()));
    }

}
